### PR TITLE
chore: configure deployment in GitHub actions

### PR DESCRIPTION
**Pull request by algomaster99**
@monperrus Now we need to configure the environment secrets.
1. SONATYPE_USER
2. SONATYPE_PASSWORD
3. SPOONBOT_PASSPHRASE

All of these are in your inbox in an encrypted file called `action-secrets.gpg`.

@slarse suggested having the GPG key as one of the secrets instead of pushing it to the repository. If the passphrase is sufficient bits long then we need not really worry.

### CODE REVIEW

**Comment by monperrus** [comment]
Cool!

> Now we need to configure the environment secrets.

@algomaster99 you're admin here, you should have the rights to do it.

**Comment by algomaster99** [comment]
Okay. I can configure the Sonatype credentials, but you need to send me the passphrase over the encrypted channel.

**Comment by monperrus** [comment]
I'm not sure to understand.

the passphrase for which GPG key? The one on gumtree-spoon-ast-diff? another one?

**Comment by algomaster99** [comment]
> The one on gumtree-spoon-ast-diff? another one?

Yes, the passphrase for [encrypted gpg key on gumtree-spoon-ast-diff](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/.buildscript/spoonbot.gpg.enc). I put _the same_ encrypted GPG key in this PR as well.

**Comment by monperrus** [comment]
Hum, I'm not sure I have it.

Just sent you one tentative passphrase over the GPG channel

**Comment by algomaster99** [comment]
> Hum, I'm not sure I have it.

I have forwarded you the e-mail. You should be able to decrypt the attached encrypted file. The passphrase is inside that.

**Comment by monperrus** [comment]
I see that I have `0EA6DE9E4988911867CA90CA1429025E3EDA19A5 ` in my key manager.

Is that the key we're talking about?

**Comment by algomaster99** [comment]
@monperrus yes! I encrypted it with a passphrase in October and I sent that passphrase to you in `action-secrets.gpg` (see your email). The encrypted version is pushed in this pull request. We need the passphrase to decrypt it.

**Review by monperrus — APPROVED** [review]
LGTM

**Comment by slarse** [comment]
> If the passphrase is sufficient bits long then we need not really worry.

Did you consult Doug on what "sufficiently long" is? I still really don't like this, it just seems so much easier, and it's much more secure, to store the key itself as a secret and let GitHub handle the encryption.

**Pull request merged**
